// export const API_URL = "http://localhost:9002/api";
// export const API_URL = "https://djueksmuee.topupskuyy.id/api";
// export const API_URL = "https://yuiertzxcv.vouchergamer.id/api";
export const API_URL = "https://xpgmfnzcta.uarstore.com/api";
// export const API_URL = "https://blnskrtrve.tokomeezy.com/api";
// export const API_URL = "https://riiwtleuaa.hexhstore.id/api";
export const API_URL = "https://jdhymxwpyf.montopup.com/api";
// export const API_URL = "https://ovtlzkbsbo.nightcrownstore.com/api";
// export const API_URL = "https://roymeemjff.harumistore.com/api"
